package com.chh.trustfort.payment.enums;

public enum Role {
    LOGIN("LOGIN"),
    ADMIN("ADMIN"),

    // Approval Rule Roles
    CREATE_APPROVAL_RULE("C_RUL"),
    UPDATE_APPROVER("U_APPROVER"),
    DELETE_APPROVAL_RULE("D_APPROVAL"),
    VIEW_APPROVAL_RULE("V_APPROVAL"),

    // Credit Line Roles
    CREATE_CREDIT_LINE("C_CREDIT"),
    VIEW_CREDIT_LINE("V_CREDIT"),
    UPDATE_CREDIT_LINE("U_CREDIT"),
    APPROVE_CREDIT_LINE("APPROVE_CREDIT_LINE"),
    CREATE_WALLET("C_WAL"),
    FUND_WALLET("F_WAL"),
    FETCH_WALLET("W_FET"),
    TRANSFER_FUNDS("T_FND"),
    CHECK_BALANCE("W_BAL"),
    TRANSACTION_HISTORY("T_HIS"),
    WITHDRAW_FUNDS("W_FND"),
    FREEZE_WALLET("W_FRZ"),
    UNFREEZE_WALLET("W_UFR"),
    CLOSE_WALLET("W_CLS"),
    LOCK_FUNDS("L_FND"),
    UNLOCK_FUNDS("U_FND"),
    CREDIT_COMMISSION("CREDIT_COMMISSION"),
    VIEW_COMMISSION("VIEW_COMMISSION"),
    GENERATE_PAYMENT_REFERENCE("G_REF"),
    GENERATE_OTP("G_OTP"),
    MOCK_FCMB_BASE("M_FCMB"),
    SIMULATE_TRANSFER_STATUS("S_TS"),
    FUND_WEBHOOK("F_WH"),
    VALIDATE_PIN("V_PN"),
    SETUP_PIN("S_PN"),
    HANDLE_WEBHOOK("H_WB"),
    HANDLE_FCMB_WEBHOOK("H_FWB"),
    INITIATE_CARD_PAYMENT("I_CP"),
    GENERATE_ACCOUNT("G_AT"),
    CONFIRM_TRANSFER("C_TF"),
    CONFIRM_BANK_TRANSFER("C_BT"),
    VERIFY_FLW_TRANSACTION("V_FT"),
    GENERATE_BALANCE_SHEET("G_BS"),
    TEST_EMAIL_NOTIFICATION("T_E_N"),
    DECRYPT("D"),
    UPDATE_WALLET_BALANCE("U_W_B"),
    PROCESS_WEBHOOK("P_W"),
    CREDIT_WALLET("C_W"),
    RETRY_FAILED_TRANSFERS("R_F_T"),
    MOCK_TRANSFER_STATUS("M_T_S"),
    INITIATE_FLW_PAYMENT("I_F_P"),
    GET_ALL_WALLETS_BY_USER_ID("W_B_U"),
    FLUTTERWAVE_WEBHOOK("F_W"), RECONCILE_BANK_TRANSFER("R_BT");


    private final String role;

    Role(String role) {
        this.role = role;
    }

    public String getValue() {
        return this.role;
    }
}
