server:
    port: 8888
    
spring:
    application:
        name: trustfort-config
    profiles:
        active: native
    cloud:
        config:
            server:
                git:
                    uri: file:///C:/Apps/trustfort/configserver

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost
    server:
        wait-time-in-ms-when-sync-empty: 0

logging:
    file:
        name: C:/chh/logs/trustfort.log
#cloud:
#    aws:
#        credentials:
#            access-key: AKIA3WKXQ6EYHFYVKMDO
#            secret-key: 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
#        region:
#            static: us-east-1
#        s3:
#            bucket: trustfort
#
#

        
