server:
    port: 1006

spring:
    application:
        name: trustfort-payment
    cloud:
        config:
            uri: http://trustfort-config:8888
            name: config-server

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
email:
  notification:
    url: https://test.chiplc.com:8443/trustfort/api/v1/adminService/send-email?htmlStatus=true

jwt:
    issuer: trustfort
    secret: QmFzZTY0LWVuY29kZWQtc2VjcmV0LWtleQ==
