package com.chh.trustfort.accounting.enums;

public enum ReportType {

    BALANCE_SHEET,
    CASH_FLOW,
    VARIANCE_REPORT,
    CONSOLIDATED_REPORT,
    EQUITY_STATEMENT,
    INCOME_STATEMENT,
    PROFIT_AND_LOSS,
    STATEMENT_OF_EQUITY, CONSOLIDATED, TRIAL_BALANCE
}
